name: Main Push Actions

on:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  checks-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Check code formatting
        run: yarn format:check

      - name: Build
        run: yarn build

      - name: Set npmAuthToken in .yarnrc.yml
        run: |
          echo "npmAuthToken: ${NODE_AUTH_TOKEN}" >> .yarnrc.yml

      - name: Publish
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Get the version from package.json
      - name: Get npm version
        id: package-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      # Create a GitHub release using gh-action-create-release
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "v${{ steps.package-version.outputs.version }}"
          prerelease: false
          title: "Release ${{ steps.package-version.outputs.version }}"
          body: "Release notes for version ${{ steps.package-version.outputs.version }}"
